name: Publish CodeIndex

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VENDOR_NAME: ${{ vars.VENDOR_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Install dependencies
        run: cd src && dotnet restore

      - name: Test CodeIndex
        run: cd src && dotnet test --no-restore --verbosity normal

      - name: Build CodeIndex
        run: git clean -xdf && cd src && dotnet clean && dotnet build CodeIndex.sln --configuration Release

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: CodeIndex.nupkgs
          path: src/**/*.nupkg

      - name: Push generated package to GitHub registry
        shell: bash
        run: find . -name '*.nupkg' | xargs -i dotnet nuget push --skip-duplicate {}
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Push generated package to NuGet.org
        shell: bash
        run: find . -name '*.nupkg' | xargs -i dotnet nuget push --skip-duplicate -s "https://api.nuget.org/v3/index.json" -k "$NUGET_AUTH_TOKEN" {}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          docker build -f ./src/CodeIndex.Server/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/codeindex:latest --build-arg VENDOR_NAME=$VENDOR_NAME .
          docker push ${{ secrets.DOCKER_USERNAME }}/codeindex:latest
