name: Publish CodeIndex

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3
        with:
          source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json
          dotnet-version: 7.0.x
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      - name: Install dependencies
        run: |
          cd src
          dotnet restore

      - name: Build CodeIndex
        run: dotnet build src/CodeIndex.sln  --configuration Release --no-restore

      - name: Test CodeIndex
        run: |
          cd src
          dotnet test --no-restore --verbosity normal

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: CodeIndex.nupkgs
          path: src/**/*.nupkg

      - name: Push generated package to GitHub registry
        shell: bash
        run: find . -name '*.nupkg' | xargs -i dotnet nuget push --skip-duplicate {}
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}

      # - name: Push generated package to NuGet.org
      #   shell: bash
      #   run: find . -name '*.nupkg' | xargs -i dotnet nuget push --skip-duplicate -s "https://api.nuget.org/v3/index.json" -k "$NUGET_AUTH_TOKEN" {}
      #   env:
      #     NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push the Docker image
        run: |
          cd src
          docker build -f CodeIndex.Server/Dockerfile -t qiuhaotc/codeindex:latest .
          docker push qiuhaotc/codeindex
